### ISSUE TITLE
[PBI] API isochrone

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/LASUR-swiss-proximity#35] opened 2022-12-13 12:06 UTC
**With open route service**
https://openrouteservice.org/
@pierreleripoll  asks for no limits (education account)

**With travel time** 
https://docs.traveltime.com/api/overview/introduction

-> define which one to use @pierreleripoll

**Comment by pierreleripoll** [comment] 2023-01-04 16:40
Closing this issue, duplicate of #36

**Closed by pierreleripoll** 2023-01-04 16:40 UTC
