### ISSUE TITLE
[PBI] test  isochorne (mode 3) service - walk and public transport

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/LASUR-swiss-proximity#10] opened 2022-11-03 07:14 UTC
User story : The use click on one localtion and the service returns the 15 min walk isochrone

Fisrt try with https://openrouteservice.org/

**Comment by pierreleripoll** [comment] 2023-01-04 16:42
Closing as duplicate of #36

**Closed by pierreleripoll** 2023-01-04 16:42 UTC
