### ISSUE TITLE
[PBI] UX App layout CSS

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/LASUR-swiss-proximity#34] opened 2022-12-13 12:04 UTC
@pierreleripoll does a first draft
@meschultheiss gives his feedback

**Comment by pierreleripoll** [comment] 2023-01-04 16:41
Closing as duplicate of #40

**Closed by pierreleripoll** 2023-01-04 16:41 UTC

**Comment by regislon** [comment] 2023-02-06 09:41
To be done : 
- [ ] transport modes in radio buttons
- [ ] Add presenation text + website content
- [ ] add simple mode
- [ ] remove one location search bar
- [ ] zoom out to see entirely Switzerland

**Comment by pierreleripoll** [comment] 2023-02-18 13:56
@regislon since this issue is closed I copy your comment to open issue #40
